apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: "slave"
spec:
  serviceAccountName: jenkins
  containers:
  - name: kubectl
    image: kamran420/jenkins-kubectl:v1
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    args:
    - sleep
    - 9999
    tty: true
